---

- name: Configure minio service env
  template:
    src: "minio.env.j2"
    dest: "/etc/default/minio"
    owner: root
    group: root
    mode: 0644

- name: Configure minio service
  template:
    src: "minio.service.j2"
    dest: "/usr/lib/systemd/system/minio.service"
    owner: root
    group: root
    mode: 0644
#  notify:
#    - systemd daemon reload
#    - restart minio

- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
       {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  loop:
    - { name: minio-1, ip: 192.168.88.60 }
    - { name: minio-2, ip: 192.168.88.63 }
  notify:
    - systemd daemon reload
    - restart minio


...